// Report assembly: DOM rendering, Print to PDF, Markdown download.

import { renderRadarChart, buildAccessibleTable } from './chart.js';
import { formatScore } from './scoring.js';

const HORIZON_LABELS = {
  do_now:        'Do now',
  next_6_months: 'Next 6 months',
  strategic:     'Strategic (12 months+)',
};

const PRIORITY_LABELS = {
  quick_win:   'Quick win',
  foundational:'Foundational',
  strategic:   'Strategic',
};

const EFFORT_LABELS = { S: 'Small', M: 'Medium', L: 'Large' };

function esc(str) {
  return String(str ?? '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// ─── DOM Report ───────────────────────────────────────────────────────────────

/**
 * Render the full report into #report-container.
 */
export function renderReport(container, { scores, recommendations, narrative, dimensions, maturityLevels, content, contextAnswers }) {
  const orgName = contextAnswers.org_name ? `${esc(contextAnswers.org_name)} — ` : '';
  const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });

  container.innerHTML = `
    <div class="report-content" id="report-content">

      <!-- Header -->
      <div class="report-header print-full-width">
        <div class="flex items-center gap-3 mb-2">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 40" width="45" height="30" aria-hidden="true">
            <rect width="60" height="40" fill="#0065BD" rx="2"/>
            <line x1="0" y1="0" x2="60" y2="40" stroke="white" stroke-width="8"/>
            <line x1="60" y1="0" x2="0" y2="40" stroke="white" stroke-width="8"/>
          </svg>
          <div>
            <h1 class="text-2xl font-bold text-gray-900">Data Architecture Maturity Report</h1>
            <p class="text-sm text-gray-500">${orgName}${date}</p>
          </div>
        </div>
      </div>

      <!-- Overall score -->
      <section class="report-section" aria-labelledby="overall-heading">
        <h2 id="overall-heading">Overall maturity</h2>
        <div class="overall-score-display">
          <span class="score-number" aria-label="Overall score: ${formatScore(scores.overall.score)} out of 5">
            ${formatScore(scores.overall.score)}
          </span>
          <span class="score-denom">/5</span>
          <span class="score-label">${getLevelLabel(scores.overall.level, maturityLevels)}</span>
        </div>
        <p class="narrative-text">${esc(narrative.executiveSummary)}</p>
        ${narrative.contextObservations.length > 0 ? `
          <div class="context-observations">
            ${narrative.contextObservations.map(o => `<p class="observation-text">${esc(o)}</p>`).join('')}
          </div>` : ''}
      </section>

      <!-- Radar chart -->
      <section class="report-section" aria-labelledby="chart-heading">
        <h2 id="chart-heading">Scores by dimension</h2>
        <div class="chart-wrapper">
          <canvas id="radar-chart" role="img" aria-label="Radar chart of maturity scores by dimension"></canvas>
        </div>
        <details class="mt-4">
          <summary class="text-sm text-gray-500 cursor-pointer hover:text-gray-700">
            Show data table (screen reader accessible)
          </summary>
          <div id="accessible-table-container" class="mt-2">
            ${buildAccessibleTable(dimensions, scores.dimensions, maturityLevels)}
          </div>
        </details>
      </section>

      <!-- Dimension summaries -->
      <section class="report-section" aria-labelledby="dimensions-heading">
        <h2 id="dimensions-heading">Dimension detail</h2>
        <div class="dimension-grid">
          ${dimensions.map(dim => renderDimensionCard(dim, scores, narrative, maturityLevels)).join('')}
        </div>
      </section>

      <!-- Recommendations -->
      <section class="report-section" aria-labelledby="recs-heading">
        <h2 id="recs-heading">Recommendations</h2>
        ${renderRecommendationGroups(recommendations, content.tools)}
      </section>

      <!-- Closing -->
      <section class="report-section closing-section">
        <p class="narrative-text">${esc(narrative.closingRemark)}</p>
        <p class="text-sm text-gray-400 mt-4">
          Generated by the Data Architecture Maturity Assessment Tool · Apache 2.0 ·
          <a href="https://github.com/masoodalam/data-architecture-assessment" class="underline">github.com/masoodalam/data-architecture-assessment</a>
        </p>
      </section>

    </div>`;

  // Render radar chart after DOM is ready
  const canvas = container.querySelector('#radar-chart');
  if (canvas && window.Chart) {
    renderRadarChart(canvas, dimensions, scores.dimensions);
  }
}

function getLevelLabel(level, maturityLevels) {
  if (!level) return '';
  const found = (maturityLevels.levels ?? []).find(l => l.level === level);
  return found ? `Level ${level} — ${found.label}` : `Level ${level}`;
}

function renderDimensionCard(dim, scores, narrative, maturityLevels) {
  const result = scores.dimensions[dim.id] ?? {};
  const score  = formatScore(result.score);
  const label  = getLevelLabel(result.level, maturityLevels);
  const summary = narrative.dimensionSummaries[dim.id] ?? '';
  const insuffFlag = result.insufficientData
    ? '<span class="badge badge-warn">Insufficient data</span>' : '';

  return `
    <div class="dim-card" style="border-left-color: ${esc(dim.color)}">
      <div class="dim-card-header">
        <span class="dim-name">${esc(dim.label)}</span>
        <span class="dim-score" aria-label="Score ${score} out of 5">${score}/5</span>
      </div>
      <p class="dim-level">${esc(label)} ${insuffFlag}</p>
      <p class="dim-summary">${esc(summary)}</p>
    </div>`;
}

function renderRecommendationGroups(grouped, tools) {
  const toolsById = Object.fromEntries((tools ?? []).map(t => [t.id, t]));
  const sections = Object.entries(HORIZON_LABELS)
    .filter(([key]) => grouped[key]?.length > 0)
    .map(([key, label]) => `
      <div class="rec-horizon-group">
        <h3 class="rec-horizon-label">${esc(label)}</h3>
        ${grouped[key].map(rec => renderRecommendationCard(rec, toolsById)).join('')}
      </div>`)
    .join('');

  if (!sections) return '<p class="text-gray-500">No recommendations matched your profile.</p>';
  return sections;
}

function renderRecommendationCard(rec, toolsById) {
  const primaryTool = rec.primary_tool ? toolsById[rec.primary_tool] : null;
  const toolLink = primaryTool
    ? `<a href="${esc(primaryTool.url)}" class="tool-link" target="_blank" rel="noopener noreferrer">${esc(primaryTool.name)}</a>`
    : '';
  const altTools = (rec.alternative_tools ?? [])
    .map(id => toolsById[id])
    .filter(Boolean)
    .map(t => `<a href="${esc(t.url)}" class="tool-link-alt" target="_blank" rel="noopener noreferrer">${esc(t.name)}</a>`)
    .join(', ');

  const steps = (rec.first_steps ?? [])
    .map(s => `<li>${esc(s)}</li>`)
    .join('');

  return `
    <div class="rec-card">
      <div class="rec-card-header">
        <h4 class="rec-title">${esc(rec.title)}</h4>
        <div class="rec-badges">
          <span class="badge badge-priority badge-${rec.priority}">${esc(PRIORITY_LABELS[rec.priority] ?? rec.priority)}</span>
          <span class="badge badge-effort">Effort: ${esc(EFFORT_LABELS[rec.effort] ?? rec.effort)}</span>
        </div>
      </div>
      <p class="rec-rationale">${esc(rec.rationale)}</p>
      ${steps ? `<ol class="rec-steps">${steps}</ol>` : ''}
      ${primaryTool || altTools ? `
        <div class="rec-tools">
          ${primaryTool ? `<span class="rec-tool-label">Primary tool:</span> ${toolLink}` : ''}
          ${altTools ? `<span class="rec-tool-label">Alternatives:</span> ${altTools}` : ''}
        </div>` : ''}
    </div>`;
}

// ─── Print ────────────────────────────────────────────────────────────────────

export function printReport() {
  window.print();
}

// ─── Markdown export ──────────────────────────────────────────────────────────

export function downloadMarkdown({ scores, recommendations, narrative, dimensions, maturityLevels, contextAnswers }) {
  const md = buildMarkdown({ scores, recommendations, narrative, dimensions, maturityLevels, contextAnswers });
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  const org  = contextAnswers.org_name ? `${contextAnswers.org_name.replace(/\s+/g, '-')}-` : '';
  a.href     = url;
  a.download = `${org}data-maturity-report.md`;
  a.click();
  URL.revokeObjectURL(url);
}

export function buildMarkdown({ scores, recommendations, narrative, dimensions, maturityLevels, contextAnswers }) {
  const org  = contextAnswers.org_name ? `**Organisation:** ${contextAnswers.org_name}\n\n` : '';
  const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });

  const lines = [
    `# Data Architecture Maturity Report`,
    ``,
    org + `**Date:** ${date}  `,
    `**Overall score:** ${formatScore(scores.overall.score)}/5 — ${getLevelLabel(scores.overall.level, maturityLevels)}`,
    ``,
    `---`,
    ``,
    `## Executive Summary`,
    ``,
    narrative.executiveSummary,
    ``,
    ...(narrative.contextObservations.length > 0 ? [
      ...narrative.contextObservations.map(o => `> ${o}`),
      ``,
    ] : []),
    `---`,
    ``,
    `## Scores by Dimension`,
    ``,
    `| Dimension | Score | Level | Band |`,
    `|-----------|-------|-------|------|`,
    ...dimensions.map(dim => {
      const r = scores.dimensions[dim.id] ?? {};
      const levelLabel = (maturityLevels.levels ?? []).find(l => l.level === r.level)?.label ?? '—';
      return `| ${dim.label} | ${formatScore(r.score)}/5 | ${r.level ?? '—'} | ${levelLabel} |`;
    }),
    ``,
    `---`,
    ``,
    `## Dimension Detail`,
    ``,
    ...dimensions.flatMap(dim => {
      const r = scores.dimensions[dim.id] ?? {};
      const sum = narrative.dimensionSummaries[dim.id] ?? '';
      return [
        `### ${dim.label}`,
        ``,
        `**Score:** ${formatScore(r.score)}/5 — ${getLevelLabel(r.level, maturityLevels)}${r.insufficientData ? ' *(insufficient data)*' : ''}`,
        ``,
        sum,
        ``,
      ];
    }),
    `---`,
    ``,
    `## Recommendations`,
    ``,
    ...Object.entries(HORIZON_LABELS).flatMap(([key, label]) => {
      const recs = recommendations[key] ?? [];
      if (recs.length === 0) return [];
      return [
        `### ${label}`,
        ``,
        ...recs.flatMap(rec => [
          `#### ${rec.title}`,
          ``,
          `**Priority:** ${PRIORITY_LABELS[rec.priority] ?? rec.priority} | **Effort:** ${EFFORT_LABELS[rec.effort] ?? rec.effort}`,
          ``,
          rec.rationale,
          ``,
          ...(rec.first_steps?.length ? [
            `**First steps:**`,
            ...rec.first_steps.map((s, i) => `${i + 1}. ${s}`),
            ``,
          ] : []),
          ...(rec.primary_tool ? [`**Primary tool:** ${rec.primary_tool}`, ``] : []),
        ]),
      ];
    }),
    `---`,
    ``,
    narrative.closingRemark,
    ``,
    `---`,
    ``,
    `*Generated by the [Data Architecture Maturity Assessment Tool](https://github.com/masoodalam/data-architecture-assessment) · Apache 2.0*`,
  ];

  return lines.join('\n');
}
